### ISSUE TITLE
Reorganize historian.py file

### ISSUE THREAD

**Issue by ABCambridge** [beanlab/quest_framework#21]
... @kjstanding it might be good for you to describe your work here

**Comment by kjstanding** [comment]
I moved the `History` class to `history.py` and referenced it with an import statement

**Comment by kjstanding** [comment]
I moved all the `EventRecord` typed dictionaries to `types.py` and reference them with an import all statement

**Comment by kjstanding** [comment]
I optimized the imports in `historian.py` for `History` and the types. I also changed the imports in all the other src files that imported `History` or any event record types to be a direct import instead of indirect through `historian.py`.

**Comment by kjstanding** [comment]
Might be good to look at a few functions that reside outside of the Historian class that could maybe be moved to a separate file called `utils.py`

**Comment by kjstanding** [comment]
Created PR. Under review

**Comment by kjstanding** [comment]
Dr. Bean's discord comment from 02/08:
I think the resource Q should only be created if someone is asking for the resource stream. So, when a resources is created, modified, etc, it checks if a queue for the corresponding identity exists, and if it does, puts an event on it.
There may need to be multiple Qs per identity (multiple listeners for each identity). So when `stream` is called for identity, a new queue is created and put in the list of Qs associated with that identity. 

The data would look something like:
```py
self.resource_queues = {
  'foobar': [queue1, queue2],
  None: [queue3]  # None represents the global/public identity
}
```
