### ISSUE TITLE
Ensure cleanup of deleted workflow state

### ISSUE THREAD

**Issue by easyasme** [beanlab/quest_framework#55]
Ensure that when a workflow state is deleted, all associated records and namespaces (e.g., files, tables, etc.) are correctly removed from blob storage.

**Comment by cwebbles** [comment]
- We want to make sure workflows are completing properly and being cleaned up properly. 
- await wtask <- after this it should be ready to clean up
- Quest shouldn't remember workflows so we should remove the records

history = []
(historian.run(...))
assert history is empty

- maybe try workflow manager cleaning up history after things are done?
- historian will run and when it is finished you want to make sure stuff gets cleaned up then.
